[package]
name = "wazabin-qcode-macro"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "Procedural macro for embedding QCode source in Rust"
readme = "readme.md"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/wazabin-qcode-macro"
keywords = ["binary-analysis", "macro", "pcode", "reverse-engineering"]
categories = ["development-tools", "parsing"]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.5"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
wazabin-qcode-parser.workspace = true
