[package]
name = "qcode"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "Typed SSA-style p-code IR for binary analysis, modelled after Ghidra's p-code"
repository.workspace = true

[features]
testing = []

[dependencies]
binfmt.workspace = true
inventory.workspace = true
jstd.workspace = true
pest.workspace = true
qcode_macro.workspace = true
qcode_parser.workspace = true
serde.workspace = true
log.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true

[dev-dependencies]
bincode.workspace = true
