//! The `--out DIR` artifact: `context.bin`, `graph.json`,
//! `regions/<addr>-g<gen>.bin` and the text summary.
//!
//! The directory is the whole output of a run, and it is meant to be read by
//! something other than this program:
//!
//! ```text
//! context.bin        bincode of the final Context — every block the run lifted
//! context.meta.json  { blocks, functions, bytes }, so the .bin can be sized up
//!                    without decoding it
//! graph.json         the nodes, edges, sites and regions of super::graph
//! regions/*.bin      the generated bytes themselves, one file per region
//! ```
//!
//! `context.json` is deliberately not written: the serde form of a context
//! holding a whole libc is tens of megabytes of JSON nobody reads, and
//! `context.bin` plus the meta file says the same thing.
//!
//! # Addresses
//!
//! Every guest address in `graph.json` is a `"0x..."` string: an address in
//! decimal is one nobody can match against a disassembly.

use std::{
    collections::BTreeMap,
    fmt, fs,
    path::{Path, PathBuf},
};

use qcode_userland::Process;

use super::{
    driver::Outcome,
    graph::{self, Graph, Harvest, Shadow},
    layout,
};

/// Writes the artifact directory for a finished run, and returns what the
/// one-screen summary needs.
pub fn write(dir: &Path, process: &mut Process, outcome: &Outcome) -> Result<Summary, String> {
    let fail = |what: &str, e: std::io::Error| format!("cannot write {what}: {e}");
    fs::create_dir_all(dir).map_err(|e| fail(&dir.display().to_string(), e))?;

    let vm = &*process.vm();
    let ctx = vm.context();
    let memory = vm.memory();
    let edges_recorded = outcome.options.hooks && outcome.options.edges;
    let graph = graph::harvest(&Harvest {
        ctx,
        mmu: &memory.mmu,
        shadow: outcome
            .spaces
            .map(|spaces| Shadow::new(memory.flat(), spaces.shadow, &outcome.layout)),
        layout: &outcome.layout,
        recorder: &outcome.recorder,
        log: &outcome.log,
        site_tasks: &outcome.site_tasks,
        ptrace_redirects: &outcome.ptrace_redirects,
        edges_recorded,
    });
    let mut warnings = graph.warnings.clone();

    // The context first: a harvest that then fails still leaves the IR
    // behind to look at.
    let encoded = bincode::serde::encode_to_vec(ctx, bincode::config::standard())
        .map_err(|e| format!("cannot encode the context: {e}"))?;
    let meta = ContextMeta {
        blocks: ctx.blocks().count(),
        functions: ctx.functions().count(),
        bytes: encoded.len(),
    };
    fs::write(dir.join("context.bin"), &encoded).map_err(|e| fail("context.bin", e))?;
    fs::write(dir.join("context.meta.json"), to_json(&meta)? + "\n")
        .map_err(|e| fail("context.meta.json", e))?;

    let regions_dir = dir.join("regions");
    fs::create_dir_all(&regions_dir).map_err(|e| fail("regions/", e))?;
    let mut files = Vec::new();
    for region in &graph.regions {
        let suffix = if region.kind == "data" { "-data" } else { "" };
        let name = format!("{:#x}-g{}{suffix}.bin", region.start, region.generation);
        let mut bytes = vec![0u8; region.bytes_len() as usize];
        // Generated code is usually readable and executable, but a sample is
        // free to `mprotect` it down to either one once it is written.
        if memory.mmu.read(region.start, &mut bytes).is_err()
            && memory.mmu.read_code(region.start, &mut bytes).is_err()
        {
            warnings.push(format!(
                "the generated region at {:#x} is no longer readable; \
                 regions/{name} holds zeroes",
                region.start
            ));
        }
        fs::write(regions_dir.join(&name), &bytes).map_err(|e| fail(&name, e))?;
        files.push(name);
    }

    let report = Report {
        program: Program {
            path: &outcome.path,
            entry: outcome.entry,
            exit_status: outcome.exit_status,
            stopped: &outcome.stop_reason,
            steps: outcome.steps,
            strategy: if outcome.options.jit {
                "jit"
            } else {
                "interpreter"
            },
        },
        io: Io {
            stdout: String::from_utf8_lossy(&outcome.stdout).into_owned(),
            stderr: String::from_utf8_lossy(&outcome.stderr).into_owned(),
        },
        windows: [
            WindowWire::new(outcome.layout.image_window()),
            WindowWire::new(outcome.layout.mmap_window()),
        ],
        nodes: graph.nodes.iter().map(NodeWire::new).collect(),
        edges: graph
            .edges
            .iter()
            .map(|edge| EdgeWire {
                from: edge.from,
                to: edge.to,
                kind: edge.kind,
                from_task: edge.from_task,
                to_task: edge.to_task,
                site: edge.site,
            })
            .collect(),
        sites: outcome
            .recorder
            .sites
            .iter()
            .enumerate()
            .map(|(index, site)| SiteWire {
                id: (index + 1).min(usize::from(layout::SITE_ID_MAX)) as u16,
                pc: site.pc,
                size: site.size,
            })
            .collect(),
        regions: graph
            .regions
            .iter()
            .map(|region| RegionWire {
                start: region.start,
                end: region.end,
                generation: region.generation,
                kind: region.kind,
                bytes_len: region.bytes_len(),
            })
            .collect(),
        flags: Flags {
            hooks: outcome.options.hooks,
            edges_recorded,
            crashed: outcome.crashed,
            sites_saturated: outcome.recorder.sites_saturated,
            blocks_saturated: outcome.recorder.blocks_saturated,
            evicted: outcome.evicted,
        },
        warnings: &warnings,
    };
    fs::write(dir.join("graph.json"), to_json(&report)? + "\n")
        .map_err(|e| fail("graph.json", e))?;

    Ok(Summary::new(dir, &graph, outcome, files, warnings.len()))
}

/// Renders `value` the way every file in the directory is rendered.
fn to_json<T: serde::Serialize>(value: &T) -> Result<String, String> {
    serde_json::to_string_pretty(value).map_err(|e| format!("cannot render the report: {e}"))
}

/// The one-screen answer to "what did this run unpack?".
#[derive(Debug, Clone)]
pub struct Summary {
    /// Where the artifact was written.
    pub dir: PathBuf,
    /// How many nodes the final IR justifies.
    pub nodes: usize,
    /// How many of them the run entered.
    pub executed: usize,
    /// How many *generated* nodes carry each generation from 1 up.
    pub generated: BTreeMap<u32, usize>,
    /// The regions, as `(start, end, generation, kind, file name)`.
    pub regions: Vec<(u64, u64, u32, &'static str, String)>,
    /// How many store sites the provenance hook instrumented.
    pub sites: usize,
    /// How many blocks the first-entry log holds.
    pub entries: usize,
    /// P-code operations retired.
    pub steps: u64,
    /// How many warnings the harvest raised.
    pub warnings: usize,
}

impl Summary {
    fn new(
        dir: &Path,
        graph: &Graph,
        outcome: &Outcome,
        files: Vec<String>,
        warnings: usize,
    ) -> Self {
        let generated = graph
            .nodes_per_generation()
            .into_iter()
            .filter(|(generation, _)| *generation > 0)
            .collect();
        Self {
            dir: dir.to_path_buf(),
            nodes: graph.nodes.len(),
            executed: graph.nodes.iter().filter(|node| node.executed).count(),
            generated,
            regions: graph
                .regions
                .iter()
                .zip(files)
                .map(|(region, file)| {
                    (
                        region.start,
                        region.end,
                        region.generation,
                        region.kind,
                        file,
                    )
                })
                .collect(),
            sites: outcome.recorder.sites.len(),
            entries: outcome.log.len(),
            steps: outcome.steps,
            warnings,
        }
    }
}

impl fmt::Display for Summary {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(
            f,
            "nodes:    {} lifted, {} executed",
            self.nodes, self.executed
        )?;
        if self.generated.is_empty() {
            writeln!(f, "          no generated code")?;
        }
        for (generation, count) in &self.generated {
            writeln!(f, "  gen {generation}:  {count} generated node(s)")?;
        }
        writeln!(f, "regions:  {}", self.regions.len())?;
        for (start, end, generation, kind, file) in &self.regions {
            writeln!(
                f,
                "  {kind} gen {generation}:  {start:#x}..{end:#x}, {} bytes -> regions/{file}",
                end - start
            )?;
        }
        writeln!(f, "sites:    {} store sites", self.sites)?;
        writeln!(f, "entries:  {} blocks first entered", self.entries)?;
        writeln!(f, "steps:    {}", self.steps)?;
        writeln!(f, "warnings: {}", self.warnings)?;
        write!(f, "artifact: {}", self.dir.join("graph.json").display())
    }
}

/// What `context.meta.json` says about `context.bin`.
#[derive(Debug, serde::Serialize)]
struct ContextMeta {
    blocks: usize,
    functions: usize,
    bytes: usize,
}

/// `graph.json`.
#[derive(Debug, serde::Serialize)]
struct Report<'a> {
    program: Program<'a>,
    io: Io,
    /// What provenance covered: a guest store anywhere else was sunk, and
    /// what it wrote reads as ungenerated.
    windows: [WindowWire; 2],
    nodes: Vec<NodeWire>,
    edges: Vec<EdgeWire>,
    sites: Vec<SiteWire>,
    regions: Vec<RegionWire>,
    flags: Flags,
    warnings: &'a [String],
}

#[derive(Debug, serde::Serialize)]
struct Program<'a> {
    path: &'a str,
    #[serde(serialize_with = "hex")]
    entry: u64,
    exit_status: Option<i32>,
    stopped: &'a str,
    steps: u64,
    strategy: &'static str,
}

#[derive(Debug, serde::Serialize)]
struct Io {
    stdout: String,
    stderr: String,
}

#[derive(Debug, serde::Serialize)]
struct WindowWire {
    #[serde(serialize_with = "hex")]
    start: u64,
    #[serde(serialize_with = "hex")]
    end: u64,
    bytes_len: u64,
}

impl WindowWire {
    fn new(window: layout::Window) -> Self {
        Self {
            start: window.start,
            end: window.end(),
            bytes_len: window.len,
        }
    }
}

#[derive(Debug, serde::Serialize)]
struct NodeWire {
    #[serde(serialize_with = "hex")]
    addr: u64,
    task: u32,
    version: u32,
    range: [String; 2],
    generated: bool,
    generation: u32,
    sites: Vec<u16>,
    #[serde(skip_serializing_if = "Option::is_none", serialize_with = "hex_opt")]
    bytes_hash: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    first_entry: Option<usize>,
    executed: bool,
}

impl NodeWire {
    fn new(node: &graph::Node) -> Self {
        Self {
            addr: node.addr,
            task: node.task,
            version: node.version,
            range: [format!("{:#x}", node.start), format!("{:#x}", node.end)],
            generated: node.generated,
            generation: node.generation,
            sites: node.sites.clone(),
            bytes_hash: node.bytes_hash,
            first_entry: node.first_entry,
            executed: node.executed,
        }
    }
}

#[derive(Debug, serde::Serialize)]
struct EdgeWire {
    #[serde(serialize_with = "hex")]
    from: u64,
    #[serde(serialize_with = "hex")]
    to: u64,
    kind: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    from_task: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    to_task: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    site: Option<u16>,
}

#[derive(Debug, serde::Serialize)]
struct SiteWire {
    id: u16,
    #[serde(skip_serializing_if = "Option::is_none", serialize_with = "hex_opt")]
    pc: Option<u64>,
    size: usize,
}

#[derive(Debug, serde::Serialize)]
struct RegionWire {
    #[serde(serialize_with = "hex")]
    start: u64,
    #[serde(serialize_with = "hex")]
    end: u64,
    generation: u32,
    kind: &'static str,
    bytes_len: u64,
}

#[derive(Debug, serde::Serialize)]
struct Flags {
    hooks: bool,
    edges_recorded: bool,
    crashed: bool,
    sites_saturated: bool,
    blocks_saturated: bool,
    /// Lifted blocks the machine threw away because the guest wrote over
    /// their bytes: non-zero means the sample really did modify code the VM
    /// had already translated.
    evicted: u64,
}

fn hex<S: serde::Serializer>(value: &u64, serializer: S) -> Result<S::Ok, S::Error> {
    serializer.serialize_str(&format!("{value:#x}"))
}

fn hex_opt<S: serde::Serializer>(value: &Option<u64>, serializer: S) -> Result<S::Ok, S::Error> {
    match value {
        Some(value) => serializer.serialize_str(&format!("{value:#x}")),
        None => serializer.serialize_none(),
    }
}
