//! Harvest: the node/edge graph built from the final IR and the final shadow.
//!
//! Everything here runs *after* the machine has stopped, over three sources
//! that disagree on purpose:
//!
//! - the final [`Context`], which knows every block the run ever lifted —
//!   including the ones nothing ever entered, and the ones absorption folded
//!   into a predecessor;
//! - the shadow, which says, byte by byte, which store site last wrote it;
//! - the first-entry log, which says which blocks actually *ran*, and in
//!   what order.
//!
//! The graph is the join: a [`Node`] per lifted guest address range, a
//! [`generation`](Node::generation) per node derived from the shadow, and
//! [`Region`]s — the runs of generated bytes that some node executed out of.
//!
//! # Guest instruction lengths
//!
//! The IR carries each instruction's guest *address* but no guest *length*:
//! `InstructionRef::size` is the width of the IR value the operation
//! produces, not the width of the encoding it came from. So lengths are
//! derived: every guest address the context mentions goes into one sorted
//! set, and the length of an address is the distance to the next address in
//! that set, accepted only when it is a plausible x86-64 encoding
//! ([`MAX_INSN_LEN`] bytes or fewer) and 1 otherwise.
//!
//! Inside a block that is exact — the next lifted address *is* the next
//! instruction. It is a lower bound at a block's last instruction when
//! nothing contiguous was ever lifted after it, which is the case for an
//! unconditional `jmp` or a `ret` at the end of a run: such a range ends one
//! byte into its terminator. Ranges are used to attribute bytes to nodes and
//! to seed regions, and both tolerate a short tail: a region grows out of
//! the shadow, not out of a range.
//!
//! [`Context`]: qcode::context::Context

use std::collections::{BTreeMap, BTreeSet};

use qcode::{
    context::Context,
    space::{MemorySpaceId, SpaceId},
    value::{BasicBlock, BlockId},
};
use qcode_vm::{Mmu, flat::FlatSpaces};
use rustc_hash::{FxHashMap, FxHashSet};

use super::{
    hooks::{LogEntry, Recorder},
    layout::Layout,
};

/// The longest encoding x86-64 allows, and so the longest gap between two
/// lifted addresses that can still be one instruction.
pub const MAX_INSN_LEN: u64 = 15;

/// How many blocks a unit walk visits before it gives up.
const SPAN_BLOCKS: usize = 32;

/// How far a region may grow out from the node that seeded it, in bytes.
const MAX_REGION: u64 = 4 << 20;

/// How many guest bytes a region walk reads of shadow at a time.
const CHUNK: u64 = 4096;

/// A stable hash of a run of guest bytes.
pub fn hash_bytes(bytes: &[u8]) -> u64 {
    use std::hash::Hasher;
    let mut hasher = rustc_hash::FxHasher::default();
    hasher.write(bytes);
    hasher.finish()
}

/// The provenance bytes, as the host reads them back.
///
/// The shadow is a bounded flat state space, not guest memory, so this is a
/// host buffer indexed by the offset [`Layout`] assigns each tracked guest
/// byte — one read, no MMU, and nothing the guest could have touched.
pub struct Shadow<'a> {
    flat: &'a FlatSpaces,
    space: MemorySpaceId,
    layout: &'a Layout,
}

impl<'a> Shadow<'a> {
    pub fn new(flat: &'a FlatSpaces, space: SpaceId, layout: &'a Layout) -> Self {
        Self {
            flat,
            space: MemorySpaceId::Shared(space),
            layout,
        }
    }

    /// The site ids of `start..end`, or `None` unless one window covers the
    /// whole range.
    pub fn ids(&self, start: u64, end: u64) -> Option<Vec<u16>> {
        if end <= start {
            return None;
        }
        let (offset, run) = self.layout.shadow_run(start, end)?;
        if run != end - start {
            return None;
        }
        let raw = self
            .flat
            .read_bytes(self.space, offset, 2 * run as usize)
            .ok()?;
        Some(
            raw.chunks_exact(2)
                .map(|pair| u16::from_le_bytes([pair[0], pair[1]]))
                .collect(),
        )
    }
}

/// One lifted guest address range, and what the run made of it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Node {
    /// The block's guest address: the node's identity.
    pub addr: u64,
    /// The first byte of the node's range.
    pub start: u64,
    /// One past the last byte of the node's range; see the note on lengths
    /// in the [module documentation](self).
    pub end: u64,
    /// Whether any byte of the range carries a non-zero shadow id.
    pub generated: bool,
    /// 0 for code that came off disk, `1 + max(generation of the nodes that
    /// wrote it)` otherwise.
    pub generation: u32,
    /// The distinct store sites the shadow attributes the range to.
    pub sites: Vec<u16>,
    /// A stable hash of the node's bytes as the run left them.
    pub bytes_hash: Option<u64>,
    /// The node's position in the first-entry log, when the run entered it.
    pub first_entry: Option<usize>,
    /// Whether the run entered the node.
    pub executed: bool,
}

/// One edge of the graph.
///
/// `kind` is `control_flow` or `generated_by`; `origin` distinguishes the
/// two sources of control flow, and is absent on a `generated_by` edge,
/// which has only one source — the shadow.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Edge {
    pub from: u64,
    pub to: u64,
    pub kind: &'static str,
    pub origin: Option<&'static str>,
    pub site: Option<u16>,
}

/// A maximal run of generated bytes of one generation that some executed
/// node ran out of.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Region {
    pub start: u64,
    pub end: u64,
    pub generation: u32,
}

impl Region {
    pub fn bytes_len(&self) -> u64 {
        self.end - self.start
    }
}

/// Everything the harvest makes of a finished run.
#[derive(Debug, Clone, Default)]
pub struct Graph {
    /// The nodes, by ascending address.
    pub nodes: Vec<Node>,
    /// The edges, deduplicated and sorted.
    pub edges: Vec<Edge>,
    /// The generated regions, by ascending start.
    pub regions: Vec<Region>,
    /// What the harvest could not justify: code outside the provenance
    /// windows, a node that writes itself, a generation fixed point that did
    /// not settle.
    pub warnings: Vec<String>,
}

impl Graph {
    /// How many nodes carry each generation, generation 0 included.
    pub fn nodes_per_generation(&self) -> BTreeMap<u32, usize> {
        let mut counts = BTreeMap::new();
        for node in &self.nodes {
            *counts.entry(node.generation).or_insert(0) += 1;
        }
        counts
    }

    /// The node at `addr`, if the graph has one.
    pub fn node(&self, addr: u64) -> Option<&Node> {
        self.nodes
            .binary_search_by_key(&addr, |node| node.addr)
            .ok()
            .map(|index| &self.nodes[index])
    }

    /// The edges leading into `addr` under `kind`.
    pub fn edges_into(&self, addr: u64, kind: &str) -> impl Iterator<Item = &Edge> {
        self.edges
            .iter()
            .filter(move |edge| edge.to == addr && edge.kind == kind)
    }
}

/// What the harvest reads.
pub struct Harvest<'a> {
    pub ctx: &'a Context<'static>,
    pub mmu: &'a Mmu,
    pub shadow: Option<Shadow<'a>>,
    pub layout: &'a Layout,
    pub recorder: &'a Recorder,
    pub log: &'a [LogEntry],
    /// `--edges`: without it the log has no predecessor to report, and the
    /// observed half of the control flow is absent — not wrong, absent,
    /// which is the difference that matters for indirect branches.
    pub edges_recorded: bool,
}

/// Builds the graph out of a finished run.
pub fn harvest(input: &Harvest<'_>) -> Graph {
    let lengths = address_lengths(input.ctx);
    let (mut nodes, successors) = lift_nodes(input.ctx, &lengths);
    let mut warnings = Vec::new();

    attach_shadow(&mut nodes, input.shadow.as_ref());
    attach_code(&mut nodes, input.mmu);
    attach_log(&mut nodes, input.recorder, input.log, &mut warnings);

    let owner = Owners::new(&nodes);
    let site_owner = site_owners(input.recorder, &owner);
    assign_generations(&mut nodes, &site_owner, &mut warnings);
    warn_about_provenance(&nodes, input, &mut warnings);

    // A site inside no node wrote bytes the harvest can attribute to a
    // *site* but not to a *node*, so the code it produced is generation 1
    // and the chain stops there.
    let stamped: BTreeSet<u16> = nodes
        .iter()
        .flat_map(|node| node.sites.iter().copied())
        .collect();
    let unattributed = stamped
        .iter()
        .filter(|&&id| {
            usize::from(id)
                .checked_sub(1)
                .and_then(|index| site_owner.get(index).copied().flatten())
                .is_none()
        })
        .count();
    if unattributed > 0 {
        warnings.push(format!(
            "{unattributed} store site(s) that wrote executed code are inside no \
             lifted node; what they wrote is one generation deep at most"
        ));
    }

    let edges = build_edges(
        &nodes,
        &owner,
        &successors,
        input.recorder,
        &site_owner,
        input.log,
        input.edges_recorded,
    );
    let regions = build_regions(
        &nodes,
        input.shadow.as_ref(),
        input.layout,
        &site_owner,
        &mut warnings,
    );

    Graph {
        nodes,
        edges,
        regions,
        warnings,
    }
}

/// Every guest address the context mentions, mapped to the length derived
/// for the instruction that starts there. See the [module documentation](self).
fn address_lengths(ctx: &Context<'static>) -> FxHashMap<u64, u64> {
    let mut addresses = BTreeSet::new();
    for block in ctx.blocks() {
        if let Some(address) = block.address() {
            addresses.insert(address);
        }
        for &address in ctx.block(block.id).extra_addresses() {
            addresses.insert(address);
        }
        for insn in block.instructions() {
            if let Some(address) = insn.address() {
                addresses.insert(address);
            }
        }
    }

    let sorted: Vec<u64> = addresses.into_iter().collect();
    let mut lengths = FxHashMap::default();
    for (index, &address) in sorted.iter().enumerate() {
        let length = sorted
            .get(index + 1)
            .map(|next| next - address)
            .filter(|gap| *gap <= MAX_INSN_LEN)
            .unwrap_or(1);
        lengths.insert(address, length);
    }
    lengths
}

/// The nodes the final IR justifies, and the static successors of each.
///
/// Blocks that share an address merge into one node whose range covers both.
fn lift_nodes(
    ctx: &Context<'static>,
    lengths: &FxHashMap<u64, u64>,
) -> (Vec<Node>, FxHashMap<u64, BTreeSet<u64>>) {
    let mut ranges: BTreeMap<u64, (u64, u64)> = BTreeMap::new();
    let mut successors: FxHashMap<u64, BTreeSet<u64>> = FxHashMap::default();

    for block in ctx.blocks() {
        let Some(addr) = block.address() else {
            continue;
        };
        let (range, succs) = walk_unit(ctx, lengths, block.id);
        // A block whose guest instructions are all in pieces this walk
        // cannot reach still covers the instruction it starts at.
        let one = (addr, addr + lengths.get(&addr).copied().unwrap_or(1));
        let (start, end) = range.unwrap_or(one);
        let slot = ranges.entry(addr).or_insert((start, end));
        slot.0 = slot.0.min(start).min(one.0);
        slot.1 = slot.1.max(end).max(one.1);
        successors.entry(addr).or_default().extend(succs);
    }

    let nodes = ranges
        .into_iter()
        .map(|(addr, (start, end))| Node {
            addr,
            start,
            end,
            generated: false,
            generation: 0,
            sites: Vec::new(),
            bytes_hash: None,
            first_entry: None,
            executed: false,
        })
        .collect();
    (nodes, successors)
}

/// The guest range one addressed block covers, and the addressed blocks it
/// leads to.
///
/// Neither hook splits a block, so in practice one block is one node; the
/// walk still follows address-less successors, because absorption and the
/// lifter both produce them and a future hook that splits would too. A
/// successor that *has* an address of its own is the next node, not part of
/// this one.
fn walk_unit(
    ctx: &Context<'static>,
    lengths: &FxHashMap<u64, u64>,
    entry: BlockId,
) -> (Option<(u64, u64)>, BTreeSet<u64>) {
    let mut lo = u64::MAX;
    let mut hi = 0u64;
    let mut out = BTreeSet::new();
    let mut seen = FxHashSet::default();
    let mut todo = vec![entry];

    while let Some(id) = todo.pop() {
        if !seen.insert(id) || seen.len() > SPAN_BLOCKS {
            continue;
        }
        let view = BasicBlock::from_id(ctx, id);
        for insn in view.instructions() {
            if let Some(at) = insn.address() {
                lo = lo.min(at);
                hi = hi.max(at + lengths.get(&at).copied().unwrap_or(1));
            }
        }
        let next: Vec<BlockId> = view.successors().map(|(_, to)| to).collect();
        for to in next {
            match BasicBlock::from_id(ctx, to).address() {
                Some(addr) => {
                    out.insert(addr);
                }
                None => todo.push(to),
            }
        }
    }

    ((lo < hi).then_some((lo, hi)), out)
}

/// Fills in [`Node::generated`] and [`Node::sites`] from the final shadow.
fn attach_shadow(nodes: &mut [Node], shadow: Option<&Shadow<'_>>) {
    let Some(shadow) = shadow else {
        return;
    };
    for node in nodes.iter_mut() {
        let Some(ids) = shadow.ids(node.start, node.end) else {
            continue;
        };
        let seen: BTreeSet<u16> = ids.into_iter().filter(|&id| id != 0).collect();
        node.generated = !seen.is_empty();
        node.sites = seen.into_iter().collect();
    }
}

/// Hashes each node's bytes as the run left them.
fn attach_code(nodes: &mut [Node], mmu: &Mmu) {
    for node in nodes.iter_mut() {
        let mut bytes = vec![0u8; (node.end - node.start) as usize];
        if mmu.read_code(node.start, &mut bytes).is_ok() {
            node.bytes_hash = Some(hash_bytes(&bytes));
        }
    }
}

/// Marks the nodes the run entered, in the order the log recorded them.
fn attach_log(
    nodes: &mut [Node],
    recorder: &Recorder,
    log: &[LogEntry],
    warnings: &mut Vec<String>,
) {
    let index: FxHashMap<u64, usize> = nodes
        .iter()
        .enumerate()
        .map(|(index, node)| (node.addr, index))
        .collect();

    let mut unclaimed = 0usize;
    for (position, entry) in log.iter().enumerate() {
        let Some(addr) = recorder
            .blocks
            .get(entry.k as usize)
            .and_then(|block| block.addr)
        else {
            unclaimed += 1;
            continue;
        };
        // A block the log saw at an address no node claims was absorbed into
        // a neighbour after it ran: charge it to the node that covers it.
        let at = index.get(&addr).copied().or_else(|| {
            nodes
                .iter()
                .position(|node| addr >= node.start && addr < node.end)
        });
        let Some(at) = at else {
            unclaimed += 1;
            continue;
        };
        let node = &mut nodes[at];
        if node.executed {
            continue;
        }
        node.executed = true;
        node.first_entry = Some(position);
    }
    if unclaimed > 0 {
        warnings.push(format!(
            "{unclaimed} logged block entr(ies) matched no lifted node; the final \
             IR no longer holds the code they ran"
        ));
    }
}

/// Which node, if any, owns a guest address.
struct Owners {
    /// `(start, end, index)`, by ascending start; ranges do not overlap in
    /// practice, and the first match wins when they do.
    ranges: Vec<(u64, u64, usize)>,
    by_addr: FxHashMap<u64, usize>,
}

impl Owners {
    fn new(nodes: &[Node]) -> Self {
        let mut ranges: Vec<(u64, u64, usize)> = nodes
            .iter()
            .enumerate()
            .map(|(index, node)| (node.start, node.end, index))
            .collect();
        ranges.sort_unstable();
        let by_addr = nodes
            .iter()
            .enumerate()
            .map(|(index, node)| (node.addr, index))
            .collect();
        Self { ranges, by_addr }
    }

    /// The node whose range contains `addr`.
    fn covering(&self, addr: u64) -> Option<usize> {
        let at = self.ranges.partition_point(|(start, _, _)| *start <= addr);
        (1..=at.min(SPAN_BLOCKS)).find_map(|back| {
            let (_, end, index) = self.ranges[at - back];
            (addr < end).then_some(index)
        })
    }

    fn at(&self, addr: u64) -> Option<usize> {
        self.by_addr.get(&addr).copied()
    }
}

/// The node each store site sits in, by site index.
///
/// A site that matches no node is unattributed, and the code it wrote is
/// generation 1: written by something, but by nothing this harvest can name.
fn site_owners(recorder: &Recorder, owner: &Owners) -> Vec<Option<usize>> {
    recorder
        .sites
        .iter()
        .map(|site| site.pc.and_then(|pc| owner.covering(pc)))
        .collect()
}

/// The generation of the code a site writes: one more than the generation of
/// the node the site itself lives in.
fn generation_of_site(
    nodes: &[Node],
    site_owner: &[Option<usize>],
    id: u16,
    of: Option<usize>,
) -> u32 {
    let index = usize::from(id).checked_sub(1);
    let parent = index.and_then(|index| site_owner.get(index).copied().flatten());
    match parent {
        // A node that writes itself cannot deepen itself; the self-edge is
        // reported, and contributes nothing.
        Some(parent) if Some(parent) != of => nodes[parent].generation + 1,
        _ => 1,
    }
}

/// Solves `generation = 1 + max(generation of the writers)` by iteration.
///
/// Monotone — every step can only raise a generation — so it settles in as
/// many rounds as the generation chain is deep. A cycle in the write graph
/// would not settle, so the rounds are capped and a cap that is reached is
/// reported: the generations below it are then a lower bound.
fn assign_generations(
    nodes: &mut [Node],
    site_owner: &[Option<usize>],
    warnings: &mut Vec<String>,
) {
    let generated: Vec<usize> = nodes
        .iter()
        .enumerate()
        .filter(|(_, node)| node.generated)
        .map(|(index, _)| index)
        .collect();

    for &index in &generated {
        nodes[index].generation = 1;
    }

    let mut settled = generated.is_empty();
    for _ in 0..generated.len() + 1 {
        let mut changed = false;
        for &index in &generated {
            let want = nodes[index]
                .sites
                .iter()
                .map(|&id| generation_of_site(nodes, site_owner, id, Some(index)))
                .max()
                .unwrap_or(1);
            if want != nodes[index].generation {
                nodes[index].generation = want;
                changed = true;
            }
        }
        if !changed {
            settled = true;
            break;
        }
    }
    if !settled {
        warnings.push(
            "the generation fixed point did not settle: the write graph has a \
             cycle, and the generations reported are a lower bound"
                .to_owned(),
        );
    }
}

/// The three things the harvest cannot prove and must therefore say.
///
/// Code the run executed outside the provenance windows carries no shadow at
/// all, so "not generated" is an absence of evidence rather than evidence of
/// absence; a node whose own bytes were written from an address inside it
/// rewrote itself while it was lifted; and a store site that lies in no node
/// leaves the code it wrote one generation deep at most.
fn warn_about_provenance(nodes: &[Node], input: &Harvest<'_>, warnings: &mut Vec<String>) {
    if input.shadow.is_none() {
        return;
    }
    let outside: Vec<u64> = nodes
        .iter()
        .filter(|node| node.executed && !input.layout.in_window(node.addr))
        .map(|node| node.addr)
        .collect();
    if let Some(&first) = outside.first() {
        warnings.push(format!(
            "{} executed node(s) lie outside the provenance windows, the first at \
             {first:#x}; their bytes carry no shadow and read as ungenerated",
            outside.len()
        ));
    }

    for node in nodes {
        let self_written: Vec<u64> = node
            .sites
            .iter()
            .filter_map(|&id| input.recorder.site_of(id)?.pc)
            .filter(|&pc| pc >= node.start && pc < node.end)
            .collect();
        if let Some(&pc) = self_written.first() {
            warnings.push(format!(
                "the node at {:#x} holds the store at {pc:#x} that wrote it: it \
                 modified its own code",
                node.addr
            ));
        }
    }
}

/// The two kinds of edge, deduplicated and ordered.
fn build_edges(
    nodes: &[Node],
    owner: &Owners,
    successors: &FxHashMap<u64, BTreeSet<u64>>,
    recorder: &Recorder,
    site_owner: &[Option<usize>],
    log: &[LogEntry],
    edges_recorded: bool,
) -> Vec<Edge> {
    let mut edges = BTreeSet::new();

    for node in nodes {
        for &to in successors.get(&node.addr).into_iter().flatten() {
            edges.insert(Edge {
                from: node.addr,
                to,
                kind: "control_flow",
                origin: Some("static"),
                site: None,
            });
        }
        for &id in &node.sites {
            let Some(parent) = usize::from(id)
                .checked_sub(1)
                .and_then(|index| site_owner.get(index).copied().flatten())
            else {
                continue;
            };
            edges.insert(Edge {
                from: nodes[parent].addr,
                to: node.addr,
                kind: "generated_by",
                origin: None,
                site: Some(id),
            });
        }
    }

    if edges_recorded {
        let addr_of = |k: u32| {
            recorder
                .blocks
                .get(k as usize)
                .and_then(|block| block.addr)
                .and_then(|addr| owner.at(addr).or_else(|| owner.covering(addr)))
        };
        for entry in log {
            let (Some(pred), Some(to)) = (entry.pred, addr_of(entry.k)) else {
                continue;
            };
            let Some(from) = addr_of(pred) else {
                continue;
            };
            edges.insert(Edge {
                from: nodes[from].addr,
                to: nodes[to].addr,
                kind: "control_flow",
                origin: Some("observed"),
                site: None,
            });
        }
    }

    edges.into_iter().collect()
}

/// The generated regions: maximal runs of written bytes, cut where the
/// generation of the writer changes, kept when some executed node runs out
/// of them.
fn build_regions(
    nodes: &[Node],
    shadow: Option<&Shadow<'_>>,
    layout: &Layout,
    site_owner: &[Option<usize>],
    warnings: &mut Vec<String>,
) -> Vec<Region> {
    let Some(shadow) = shadow else {
        return Vec::new();
    };
    let seeds: Vec<&Node> = nodes
        .iter()
        .filter(|node| node.executed && node.generated)
        .collect();

    // The maximal shadow runs the seeds sit in, merged: two nodes of the
    // same decrypted buffer must not each grow their own copy of it.
    let mut runs: Vec<(u64, u64)> = Vec::new();
    for node in &seeds {
        let Some(ids) = shadow.ids(node.start, node.end) else {
            continue;
        };
        let mut at = 0usize;
        while at < ids.len() {
            if ids[at] == 0 {
                at += 1;
                continue;
            }
            let mut to = at;
            while to < ids.len() && ids[to] != 0 {
                to += 1;
            }
            let lo = node.start + at as u64;
            let hi = node.start + to as u64;
            if runs.iter().any(|&(a, b)| lo >= a && hi <= b) {
                at = to;
                continue;
            }
            let lo = grow_down(shadow, layout, lo);
            let hi = grow_up(shadow, layout, hi, lo);
            if hi - lo >= MAX_REGION {
                warnings.push(format!(
                    "the generated run at {lo:#x} reached the {MAX_REGION:#x}-byte \
                     harvest limit and is reported truncated"
                ));
            }
            runs.push((lo, hi));
            at = to;
        }
    }
    runs.sort_unstable();
    runs.dedup();
    let runs = merge(runs);

    // Cut each run where the generation of the writing site changes, so that
    // a buffer one stage filled and another extended reports as two regions.
    let mut regions = Vec::new();
    for (lo, hi) in runs {
        let Some(ids) = shadow.ids(lo, hi) else {
            continue;
        };
        let mut at = 0usize;
        while at < ids.len() {
            let generation = generation_of_site(nodes, site_owner, ids[at], None);
            let mut to = at;
            while to < ids.len()
                && generation_of_site(nodes, site_owner, ids[to], None) == generation
            {
                to += 1;
            }
            let region = Region {
                start: lo + at as u64,
                end: lo + to as u64,
                generation,
            };
            if seeds
                .iter()
                .any(|node| node.start < region.end && region.start < node.end)
            {
                regions.push(region);
            }
            at = to;
        }
    }
    regions.sort_unstable();
    regions
}

/// Merges overlapping and touching intervals of a sorted list.
fn merge(runs: Vec<(u64, u64)>) -> Vec<(u64, u64)> {
    let mut merged: Vec<(u64, u64)> = Vec::with_capacity(runs.len());
    for (lo, hi) in runs {
        match merged.last_mut() {
            Some(last) if lo <= last.1 => last.1 = last.1.max(hi),
            _ => merged.push((lo, hi)),
        }
    }
    merged
}

/// The window `addr` is tracked in, as `(start, end)`.
fn window_of(layout: &Layout, addr: u64) -> Option<(u64, u64)> {
    [layout.image_window(), layout.mmap_window()]
        .into_iter()
        .find(|window| window.contains(addr))
        .map(|window| (window.start, window.end()))
}

/// The lowest address of the run of written bytes that ends at `from`.
fn grow_down(shadow: &Shadow<'_>, layout: &Layout, from: u64) -> u64 {
    let Some((start, _)) = window_of(layout, from.saturating_sub(1)) else {
        return from;
    };
    let mut at = from;
    loop {
        let room = (at - start).min(MAX_REGION - (from - at));
        let Some(ids) = fitting(room, |step| shadow.ids(at - step, at)) else {
            return at;
        };
        let written = ids.iter().rev().take_while(|&&id| id != 0).count();
        at -= written as u64;
        if written < ids.len() {
            return at;
        }
    }
}

/// One past the highest address of the run of written bytes that starts at
/// `from`, in a run that began at `lo`.
fn grow_up(shadow: &Shadow<'_>, layout: &Layout, from: u64, lo: u64) -> u64 {
    let Some((_, end)) = window_of(layout, from) else {
        return from;
    };
    let mut at = from;
    loop {
        let room = (end - at).min(MAX_REGION - (at - lo));
        let Some(ids) = fitting(room, |step| shadow.ids(at, at + step)) else {
            return at;
        };
        let written = ids.iter().take_while(|&&id| id != 0).count();
        at += written as u64;
        if written < ids.len() {
            return at;
        }
    }
}

/// The shadow of the largest chunk of at most [`CHUNK`] bytes, out of
/// `room`, that `read` can serve.
fn fitting(room: u64, read: impl Fn(u64) -> Option<Vec<u16>>) -> Option<Vec<u16>> {
    let mut step = CHUNK.min(room);
    while step > 0 {
        if let Some(ids) = read(step) {
            return Some(ids);
        }
        step /= 2;
    }
    None
}
