[package]
name = "wazabin-qcode-parser"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
description = "Parser for the QCode text format"
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/wazabin-qcode-parser"
keywords = ["binary-analysis", "parser", "pcode", "reverse-engineering"]
categories = ["parsing"]

[dependencies]
pest.workspace = true
pest_derive.workspace = true
