name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check out path dependencies
        run: |
          git clone --depth=1 "https://github.com/${{ github.repository_owner }}/jstd.git" ../jstd
          git clone --depth=1 "https://github.com/${{ github.repository_owner }}/wazabin-binary.git" ../wazabin-binary
          git clone --depth=1 "https://github.com/${{ github.repository_owner }}/wazabin-cabi.git" ../wazabin-cabi
          git clone --depth=1 "https://github.com/${{ github.repository_owner }}/wazabin-pcode.git" ../wazabin-pcode
          git clone --depth=1 "https://github.com/${{ github.repository_owner }}/wazabin-sleigh.git" ../wazabin-sleigh
          git clone --depth=1 "https://github.com/${{ github.repository_owner }}/wazabin.git" ../wazabin
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --workspace --all-features
